In [1]:
import pandas as pd 
import numpy as np

In [2]:
!pip install numpy pandas openpyxl matplotlib seaborn scikit-learn statsmodels xgboost lightgbm sqlalchemy pymysql

Requirement already satisfied: numpy in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.3)
Requirement already satisfied: pandas in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.6)
Requirement already satisfied: openpyxl in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: matplotlib in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.11.2)
Requirement already satisfied: seaborn in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.1)
Requirement already satisfied: statsmodels in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.15.0)
Requirement already satisfied: xgboost in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.4.1)
Requirement already satisfied: lightgbm in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (4.7.0)
Requirement already satisfied: sqlalchemy in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.1.3)
Requirement already satisfied: pymysql in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: et-xmlfile in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.66.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from statsmodels) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from statsmodels) (1.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: interface-meta>=1.2.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from formulaic>=1.1.0->statsmodels) (2.0.1)
Requirement already satisfied: wrapt>=1.17.0rc1 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from formulaic>=1.1.0->statsmodels) (2.5.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in C:\Users\gupta\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
df = pd.read_excel('Churn_Unclean_Project.xlsx')

In [4]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [5]:
df.shape

(542, 18)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    str
 1   Customer_Name          533 non-null    str
 2   Gender                 536 non-null    str
 3   Age                    536 non-null    float64
 4   State                  531 non-null    str
 5   City                   539 non-null    str
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    str
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    str
 11  Payment_Method         526 non-null    str
 12  Internet_Service       535 non-null    str
 13  Tech_Support           530 non-null    str
 14  Senior_Citizen         534 non-null    str
 15  Dependents             539 non-null    str
 16  Churn                  538 non-null    str
 17  Last_Interaction_Date  539 non-null    str
dtypes: float64(4), str(14)
memory usage: 76.3 KB

In [7]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [8]:
df.duplicated().sum()

np.int64(7)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.shape

(535, 18)

In [11]:
df.replace(['N/A','NULL','',' '],np.nan,inplace=True)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [12]:
df.isnull().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      5
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [13]:
df= df.apply(lambda x: x.str.strip() if x.dtype=="object" else x)

In [14]:
df['Customer_Name']= df['Customer_Name'].str.title().str.title()
df['State']= df['State'].str.strip().str.title()
df['City']= df['City'].str.strip().str.title()
df['Gender']= df['Gender'].str.strip().str.title()
df['Subscription_Type']= df['Subscription_Type'].str.strip().str.title()
df['Contract_Type']= df['Contract_Type'].str.strip().str.title()
df['Churn']= df['Churn'].str.strip().str.title()
df['Internet_Service']= df['Internet_Service'].str.strip().str.title()
df['Payment_Method']= df['Payment_Method'].str.strip().str.title()
df['Senior_Citizen']=df['Senior_Citizen'].str.strip().str.title()

In [15]:
df['Subscription_Type'].value_counts()

Subscription_Type
Premium     184
Basic       171
Standard    169
Name: count, dtype: int64

In [16]:
col= ['Age','Tenure_Months','Monthly_Charges','Total_Charges']
for c in col:
    df[c]= pd.to_numeric(df[c],errors="coerce")

In [17]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  529.000000     528.000000       523.000000     527.000000
mean    44.328922      36.518939      1329.967285   49739.683890
std     18.635396      20.659332       713.450173   41633.677902
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.420000   18818.270000
50%     44.000000      38.000000      1295.880000   40649.600000
75%     57.000000      54.000000      1879.020000   75126.770000
max    165.000000      72.000000      2492.510000  171429.830000

In [18]:
df= df[(df['Age']>=18) & (df['Age']<=100)]

In [19]:
df= df[df['Monthly_Charges']>=0]
df= df[df['Total_Charges']>=0]

In [20]:
df.shape

(492, 18)

In [21]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  492.000000     487.000000       492.000000     492.000000
mean    43.191057      36.059548      1359.222033   50363.987561
std     15.401619      20.465130       653.133221   39760.135287
min     18.000000       1.000000       302.540000     354.120000
25%     30.000000      19.000000       762.940000   19129.100000
50%     43.000000      38.000000      1308.510000   40668.695000
75%     56.000000      53.000000      1889.437500   74393.410000
max     70.000000      72.000000      2492.510000  171429.830000

In [22]:
df['Last_Interaction_Date']= pd.to_datetime(df['Last_Interaction_Date'],errors='coerce')

In [23]:
df["Tech_Support"]=df["Tech_Support"].fillna("No")

df["Payment_Method"]=df["Payment_Method"].fillna("Unknown")

df["Monthly_Charges"]=df["Monthly_Charges"].fillna(df['Monthly_Charges'].mean())

df["Tenure_Months"]=df["Tenure_Months"].fillna(df['Tenure_Months'].mean())

df['Age'] = df['Age'].fillna(df['Age'].mean())

In [24]:
df["customer_value"]=df["Monthly_Charges"]*df["Tenure_Months"]

In [25]:
df.head(10)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,customer_value
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,2025-12-10,93627.08
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,NaT,7215.39
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,Upi,Dsl,Yes,No,No,No,NaT,140618.10
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,NaT,125182.26
8,C1008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,Two Year,Unknown,Fiber,Yes,No,No,No,NaT,75600.00
10,C1010,Anjali Mehta,Male,60.0,Delhi,Delhi,12.0,Standard,934.28,11411.36,Two Year,Credit Card,Dsl,No,Yes,No,Yes,2025-03-10,11211.36
14,C1014,Rahul Singh,Male,41.0,Karnataka,Mysuru,16.0,Premium,2226.93,35184.88,Two Year,Net Banking,Cable,Yes,No,No,No,2025-05-10,35630.88
15,C1015,Pooja Singh,Male,50.0,Delhi,Noida,16.0,Basic,576.03,9489.48,One Year,Cash,5G,No,No,No,No,2026-01-01,9216.48
18,C1018,Amit Sharma,NaN,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-To-Month,Net Banking,Fiber,Yes,No,Yes,No,2025-04-06,111759.36

In [26]:
df["Monthly_revenue"]= df["Monthly_Charges"]

In [27]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,customer_value,Monthly_revenue
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,NaT,7215.39,555.03
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,Upi,Dsl,Yes,No,No,No,NaT,140618.10,2008.83
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,NaT,125182.26,2196.18

In [28]:
df["Tenure_Group"]=pd.cut(
df["Tenure_Months"],
bins=[0,12,24,48,72],
labels=["0-12","13-24","25-48","49-72"]
)

In [29]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,customer_value,Monthly_revenue,Tenure_Group
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Upi,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,Debit Card,5G,No,No,No,Yes,NaT,7215.39,555.03,13-24
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Upi,Dsl,Yes,No,No,No,NaT,140618.10,2008.83,49-72
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Cash,Cable,Yes,Yes,Yes,No,NaT,125182.26,2196.18,49-72

In [30]:
df["Senior_Flag"]=np.where(df["Age"]>=60,"Senior","Adult")

In [31]:
df['churn_flag']= df['Churn'].map({"Yes":1,"No":0})

In [32]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,customer_value,Monthly_revenue,Tenure_Group,Senior_Flag,churn_flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72,Adult,0.0
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,NaT,7215.39,555.03,13-24,Adult,1.0
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12,Adult,0.0
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Yes,No,No,No,NaT,140618.10,2008.83,49-72,Adult,0.0
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,NaT,125182.26,2196.18,49-72,Senior,0.0

In [33]:
df['Last_Interaction_Date']=df['Last_Interaction_Date'].fillna(df['Last_Interaction_Date'].median())

In [34]:
df.info()
df['Contract_Type'] = df['Contract_Type'].str.strip().str.title()
df['Internet_Service'] = df['Internet_Service'].str.strip().str.title()

<class 'pandas.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    str
 1   Customer_Name          487 non-null    str
 2   Gender                 488 non-null    str
 3   Age                    492 non-null    float64
 4   State                  485 non-null    str
 5   City                   487 non-null    str
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    str
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    str
 11  Payment_Method         492 non-null    str
 12  Internet_Service       486 non-null    str
 13  Tech_Support           492 non-null    str
 14  Senior_Citizen         486 non-null    str
 15  Dependents             491 non-null    str
 16  Churn                  490 non-null    str
 17  Last_Interaction_Date  492 non-null    datetime64[us]
 18  customer_value         492 non-null    float64
 19  Monthly_revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    str
 22  churn_flag             490 non-null    float64
dtypes: category(1), datetime64[us](1), float64(7), str(14)
memory usage: 88.9 KB

In [35]:
df.to_csv("clean_churn_data.csv",index=False)

In [36]:
from sqlalchemy import create_engine

engine=create_engine(
"mysql+pymysql://root:Ankitraj12345@localhost/churndb"
)

In [37]:
df.to_sql(
name="customer_churn",
con=engine,
if_exists="replace",
index=False
)

492